kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.244.0.0/16"
nodes:
- role: control-plane
  extraMounts:
    - hostPath: ./queue-data
      containerPath: /var/lib/queue-data
- role: worker
  extraMounts:
    - hostPath: ./queue-data
      containerPath: /var/lib/queue-data
- role: worker
  extraMounts:
    - hostPath: ./queue-data
      containerPath: /var/lib/queue-data
- role: worker
  extraMounts:
    - hostPath: ./queue-data
      containerPath: /var/lib/queue-data
kubeadmConfigPatches:
  - |
    kind: KubeletConfiguration
    apiVersion: kubelet.config.k8s.io/v1beta1
    maxPods: 250
